In [1]:
import pandas as pd
import os
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

### Equity

(Change the filepath below to point to this month's data)

In [2]:
filepath = r'P:\Datastore02\Analytics\230 Inpatient Quality Composite\data\Equity Data\fy23\010_june_fytd'

In [3]:
nm_medicare_ids = ['140116','140130','140211','140242','140281','140286','141340','149916','140062']

### Check completeness files for existence of our hospitals

In [4]:
result_frame = []
for i, item in enumerate(os.listdir(filepath)):
    if (item.endswith('.zip')  == False) and (item.endswith('xlsx') == False) and (item != 'archive'):
        for j, item2 in enumerate(os.listdir(os.path.join(filepath,item))):
            if (item2.endswith('Completeness.csv') == True or item2.endswith('Completenes.csv') == True or item2.endswith('completeness.csv') == True) and (item2.endswith('.xlsx') == False):
                df = pd.read_csv(os.path.join(filepath,item,item2))
                nm_df = df[df['MedicareId'].isin(nm_medicare_ids)]
                print(nm_df.head())
                if nm_df.shape[0] > 0:
                    result_frame.append(nm_df)

Empty DataFrame
Columns: [MedicareId, keyword, Reason]
Index: []
     MedicareId keyword                                         Reason
630      140116      MB                                             LV
683      140116      MB  Failed a data quality due to lack of lab data
     MedicareId keyword                                         Reason
180      141340     LAQ                                             LV
202      141340     LAQ  Failed a data quality due to lack of lab data
     MedicareId keyword                                         Reason
78       141340   TROPO  Failed a data quality due to lack of lab data
105      141340   TROPO                                             LV

In [5]:
result_frame

[     MedicareId keyword                                         Reason
 630      140116      MB                                             LV
 683      140116      MB  Failed a data quality due to lack of lab data,
      MedicareId keyword                                         Reason
 180      141340     LAQ                                             LV
 202      141340     LAQ  Failed a data quality due to lack of lab data,
      MedicareId keyword                                         Reason
 78       141340   TROPO  Failed a data quality due to lack of lab data
 105      141340   TROPO                                             LV]

In [6]:
pd.options.display.max_colwidth = 300
pd.concat(result_frame).drop_duplicates()

     MedicareId keyword                                         Reason
630      140116      MB                                             LV
683      140116      MB  Failed a data quality due to lack of lab data
180      141340     LAQ                                             LV
202      141340     LAQ  Failed a data quality due to lack of lab data
78       141340   TROPO  Failed a data quality due to lack of lab data
105      141340   TROPO                                             LV

In [7]:
result_frame = []
for i, item in enumerate(os.listdir(filepath)):
    
    if (item.endswith('.zip')  == False) and (item.endswith('xlsx') == False) and (item != 'archive'):
        for j, item2 in enumerate(os.listdir(os.path.join(filepath,item))):
            
            if (item2.endswith('PHI.csv') == True):
                print(item2)
                df = pd.read_csv(os.path.join(filepath,item,item2))
                df['measure'] = item2
                result_frame.append(df[['medicareid','dischargemonth','measure']].drop_duplicates().sort_values(['medicareid','dischargemonth']))
                
                #df = df[df['dischargemonth'].isin(keep_months)]
                #df = df[['medicareid','recordid','dischargemonth']]
                #df2 = df.groupby(['medicareid','dischargemonth']).nunique('recordid').reset_index()
                #print(df2)
                #df3 = df2.groupby(['medicareid']).mean('recordid').reset_index()
                #print(df3[df3['medicareid'].isin(['149916','140116'])][['medicareid','recordid']])

CHF_PHI.csv
MB_PHI.csv
Sepsis_PHI.csv
Troponin_PHI.csv

In [8]:
pd.options.display.max_colwidth = 300
equity_df = pd.concat(result_frame).drop_duplicates()

In [9]:
equity_df.groupby('measure').nunique('medicareid')

                  medicareid  dischargemonth
measure
CHF_PHI.csv                9              11
MB_PHI.csv                 8              11
Sepsis_PHI.csv             8              11
Troponin_PHI.csv           8              11

In [10]:
equity_df.groupby(['measure','medicareid']).max().reset_index()

             measure  medicareid  dischargemonth
0        CHF_PHI.csv      140062          202305
1        CHF_PHI.csv      140116          202305
2        CHF_PHI.csv      140130          202305
3        CHF_PHI.csv      140211          202305
4        CHF_PHI.csv      140242          202305
5        CHF_PHI.csv      140281          202305
6        CHF_PHI.csv      140286          202305
7        CHF_PHI.csv      141340          202305
8        CHF_PHI.csv      149916          202305
9         MB_PHI.csv      140062          202305
10        MB_PHI.csv      140130          202305
11        MB_PHI.csv      140211          202305
12        MB_PHI.csv      140242          202305
13        MB_PHI.csv      140281          202305
14        MB_PHI.csv      140286          202305
15        MB_PHI.csv      141340          202209
16        MB_PHI.csv      149916          202305
17    Sepsis_PHI.csv      140062          202305
18    Sepsis_PHI.csv      140116          202305
19    Sepsis_PHI.csv      140130          202305
20    Sepsis_PHI.csv      140211          202305
21    Sepsis_PHI.csv      140242          202305
22    Sepsis_PHI.csv      140281          202305
23    Sepsis_PHI.csv      140286          202305
24    Sepsis_PHI.csv      149916          202305
25  Troponin_PHI.csv      140062          202305
26  Troponin_PHI.csv      140116          202305
27  Troponin_PHI.csv      140130          202305
28  Troponin_PHI.csv      140211          202305
29  Troponin_PHI.csv      140242          202305
30  Troponin_PHI.csv      140281          202305
31  Troponin_PHI.csv      140286          202305
32  Troponin_PHI.csv      149916          202305

In [11]:
equity_df.groupby(['measure','medicareid']).min().reset_index()

             measure  medicareid  dischargemonth
0        CHF_PHI.csv      140062          202207
1        CHF_PHI.csv      140116          202207
2        CHF_PHI.csv      140130          202207
3        CHF_PHI.csv      140211          202207
4        CHF_PHI.csv      140242          202207
5        CHF_PHI.csv      140281          202207
6        CHF_PHI.csv      140286          202207
7        CHF_PHI.csv      141340          202208
8        CHF_PHI.csv      149916          202207
9         MB_PHI.csv      140062          202207
10        MB_PHI.csv      140130          202207
11        MB_PHI.csv      140211          202207
12        MB_PHI.csv      140242          202207
13        MB_PHI.csv      140281          202207
14        MB_PHI.csv      140286          202207
15        MB_PHI.csv      141340          202207
16        MB_PHI.csv      149916          202207
17    Sepsis_PHI.csv      140062          202207
18    Sepsis_PHI.csv      140116          202207
19    Sepsis_PHI.csv      140130          202207
20    Sepsis_PHI.csv      140211          202207
21    Sepsis_PHI.csv      140242          202207
22    Sepsis_PHI.csv      140281          202207
23    Sepsis_PHI.csv      140286          202207
24    Sepsis_PHI.csv      149916          202207
25  Troponin_PHI.csv      140062          202207
26  Troponin_PHI.csv      140116          202207
27  Troponin_PHI.csv      140130          202207
28  Troponin_PHI.csv      140211          202207
29  Troponin_PHI.csv      140242          202207
30  Troponin_PHI.csv      140281          202207
31  Troponin_PHI.csv      140286          202207
32  Troponin_PHI.csv      149916          202207

### Lab

In [13]:
filepath = r'P:\Datastore02\Analytics\230 Inpatient Quality Composite\data\Lab Data\fy23\010_june_fytd'

In [14]:
result_frame = []
for i, item in enumerate(os.listdir(filepath)):
    if (item.endswith('.zip')  == False) and (item.endswith('xlsx') == False) and (item != 'archive'):
        for j, item2 in enumerate(os.listdir(os.path.join(filepath,item))):
            
            if (item2.endswith('Completeness.csv') == True or item2.endswith('Completenes.csv') == True or item2.endswith('completeness.csv') == True) and (item2.endswith('.xlsx') == False):
                print(item2)
                try:
                    df = pd.read_csv(os.path.join(filepath,item,item2))
                    #print(df.head())
                    try:
                        nm_df = df[df['MedicareId'].isin(nm_medicare_ids)]
                    except:
                        nm_df = df[df['MedicareId'].isin(nm_medicare_ids)]
                    #print(nm_df.head())
                    if nm_df.shape[0] > 0:
                        result_frame.append(nm_df)
                except:
                    pass

Hypoglycemia_Completeness.csv
Hypoglycemia_Completeness.csv
Lactate_Completenes.csv
Lactate_Completenes.csv
Transfusion_Completeness.csv
Transfusion_Completeness.csv
Warfarin_Completeness.csv
Warfarin_Completeness.csv

In [15]:
result_frame

[    MedicareId keyword                                              Reason
 33      141340  SEPSIS                                                  LV
 65      141340  SEPSIS  Failed a data quality check but has Drugs and Labs,
      MedicareId keyword                                              Reason
 60       141340  SEPSIS  Failed a data quality check but has Drugs and Labs
 227      141340  SEPSIS                                                  LV]

In [16]:
pd.options.display.max_colwidth = 300
#pd.concat(result_frame).drop_duplicates()

In [17]:
result_frame = []
for i, item in enumerate(os.listdir(filepath)):
    
    if (item.endswith('.zip')  == False) and (item.endswith('xlsx') == False) and (item != 'archive'):
        for j, item2 in enumerate(os.listdir(os.path.join(filepath,item))):
            
            if (item2.endswith('PHI.csv') == True):
                print(item2)
                
                try:
                    df = pd.read_csv(os.path.join(filepath,item,item2))
                    df['measure'] = item2
                    if item2 in ['Warfarin_Numerator_PHI.csv','Warfarin_Denominator_PHI.csv']:
                        if 'Medicareid' in df.columns:
                            df = df.rename(columns={'Medicareid': 'MedicareId'})
                        result_frame.append(df[['MedicareId','dischargemonth','measure']].drop_duplicates().sort_values(['MedicareId','dischargemonth']))
                        #print(df[['Medicareid','dischargemonth','measure']].head())
                    result_frame.append(df[['MedicareId','dischargemonth','measure']].drop_duplicates().sort_values(['MedicareId','dischargemonth']))
                    #print(df[['MedicareId','dischargemonth','measure']].head())
                except:
                    pass
                #df = df[df['dischargemonth'].isin(keep_months)]
                #df = df[['medicareid','recordid','dischargemonth']]
                #df2 = df.groupby(['medicareid','dischargemonth']).nunique('recordid').reset_index()
                #print(df2)
                #df3 = df2.groupby(['medicareid']).mean('recordid').reset_index()
                #print(df3[df3['medicareid'].isin(['149916','140116'])][['medicareid','recordid']])

Hypoglycemia_Denominator_PHI.csv
Hypoglycemia_Numerator_PHI.csv
Hypoglycemia_Denominator_PHI.csv
Hypoglycemia_Numerator_PHI.csv
Lactate_Denominator_PHI.csv
Lactate_Numerator_PHI.csv
Lactate_Denominator_PHI.csv
Lactate_Numerator_PHI.csv
Transfusion_Denominator_PHI.csv
Transfusion_Numerator_PHI.csv
Transfusion_Denominator_PHI.csv
Transfusion_Numerator_PHI.csv
Warfarin_Denominator_PHI.csv
Warfarin_Numerator_PHI.csv
Warfarin_Denominator_PHI.csv
Warfarin_Numerator_PHI.csv

In [18]:
pd.options.display.max_colwidth = 300
lab_df = pd.concat(result_frame).drop_duplicates()

In [19]:
lab_df.groupby('measure').nunique('MedicareId')

                                  MedicareId  dischargemonth
measure
Hypoglycemia_Denominator_PHI.csv          10              11
Hypoglycemia_Numerator_PHI.csv             8              11
Lactate_Denominator_PHI.csv                8              11
Lactate_Numerator_PHI.csv                  8              11
Transfusion_Denominator_PHI.csv            9              11
Transfusion_Numerator_PHI.csv              8               8
Warfarin_Denominator_PHI.csv              10              11
Warfarin_Numerator_PHI.csv                 7              10

In [20]:
lab_df.groupby(['measure','MedicareId']).max()

                                             dischargemonth
measure                          MedicareId
Hypoglycemia_Denominator_PHI.csv 140062              202305
                                 140116              202305
                                 140130              202305
                                 140211              202305
                                 140242              202305
                                 140281              202305
                                 140286              202305
                                 141340              202305
                                 149816              202305
                                 149916              202305
Hypoglycemia_Numerator_PHI.csv   140062              202305
                                 140116              202305
                                 140130              202305
                                 140211              202305
                                 140242              202305
                                 140281              202305
                                 140286              202305
                                 149916              202305
Lactate_Denominator_PHI.csv      140062              202305
                                 140116              202305
                                 140130              202305
                                 140211              202305
                                 140242              202305
                                 140281              202305
                                 140286              202305
                                 149916              202305
Lactate_Numerator_PHI.csv        140062              202305
                                 140116              202305
                                 140130              202305
                                 140211              202305
                                 140242              202305
                                 140281              202305
                                 140286              202305
                                 149916              202304
Transfusion_Denominator_PHI.csv  140062              202305
                                 140116              202305
                                 140130              202305
                                 140211              202305
                                 140242              202305
                                 140281              202305
                                 140286              202305
                                 141340              202303
                                 149916              202305
Transfusion_Numerator_PHI.csv    140062              202209
                                 140116              202210
                                 140130              202210
                                 140211              202305
                                 140242              202303
                                 140281              202304
                                 140286              202304
                                 149916              202301
Warfarin_Denominator_PHI.csv     140062              202305
                                 140116              202305
                                 140130              202305
                                 140211              202305
                                 140242              202305
                                 140281              202305
                                 140286              202305
                                 141340              202305
                                 149816              202305
                                 149916              202305
Warfarin_Numerator_PHI.csv       140062              202304
                                 140116              202303
                                 140130              202212
                                 140211              202304
                                 140242              202304
                                 140281              202304
                                 149916              202304

In [21]:
lab_df.groupby(['measure','MedicareId']).min()

                                             dischargemonth
measure                          MedicareId
Hypoglycemia_Denominator_PHI.csv 140062              202207
                                 140116              202207
                                 140130              202207
                                 140211              202207
                                 140242              202207
                                 140281              202207
                                 140286              202207
                                 141340              202207
                                 149816              202207
                                 149916              202207
Hypoglycemia_Numerator_PHI.csv   140062              202207
                                 140116              202208
                                 140130              202207
                                 140211              202207
                                 140242              202207
                                 140281              202207
                                 140286              202207
                                 149916              202207
Lactate_Denominator_PHI.csv      140062              202207
                                 140116              202207
                                 140130              202207
                                 140211              202207
                                 140242              202207
                                 140281              202207
                                 140286              202207
                                 149916              202207
Lactate_Numerator_PHI.csv        140062              202207
                                 140116              202208
                                 140130              202207
                                 140211              202207
                                 140242              202207
                                 140281              202207
                                 140286              202207
                                 149916              202207
Transfusion_Denominator_PHI.csv  140062              202207
                                 140116              202207
                                 140130              202207
                                 140211              202207
                                 140242              202207
                                 140281              202207
                                 140286              202207
                                 141340              202207
                                 149916              202207
Transfusion_Numerator_PHI.csv    140062              202209
                                 140116              202210
                                 140130              202210
                                 140211              202305
                                 140242              202212
                                 140281              202208
                                 140286              202304
                                 149916              202301
Warfarin_Denominator_PHI.csv     140062              202207
                                 140116              202207
                                 140130              202207
                                 140211              202207
                                 140242              202207
                                 140281              202207
                                 140286              202207
                                 141340              202207
                                 149816              202210
                                 149916              202207
Warfarin_Numerator_PHI.csv       140062              202208
                                 140116              202207
                                 140130              202209
                                 140211              202207
                                 140242              202208
                                 140281              202207
                                 149916              202207